[google_credentials]
type = "service_account"
project_id = "mood-log-458400"
private_key_id = "e499aa015970fd0804f52a20a26ebc17ffdbfee0"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCqXMJ0cr5hX1OB
9MYw8N2G5udvp4YJRSyhtxV9SByXSrvaNACjzjyrYh18ANXyq8C6wBw1T/b4p1sn
MQ8mvQ9BcQYp/vAKZwRmYk9hY8jQAGp3kKNxOgjLGkMabrp0h8yESTuuv2vcY86t
lkk5It3dpzEQDe8msaihqJ36sBNUHkh+DSF+b6JETy2JlODLKXyTj1GAv4DnWf5p
mmDCP6+4ZCZtAdOm0sZ9NvxUnKrxihX4zF3eGeH/V/2sjKFpypVFlXjNnjPJwsaX
A2f7aaB9MQGAj09kjbigZb4IkqRluutRPCS221iP10uocjxEENEUbc59gRs/7RRl
KzlLRoupAgMBAAECggEADRnfztx1mU+fQITSOniFcq6+YMrjXwJhs6h8l7M0Vqql
vlqmK3KsXfooPg1i5pvwcPQd3zgwbBATrZSDX6Vln1DZqmBbdZNVRmncRKcrrdpA
VcRK22XdAAB7pVRbVKOOVeR7WV2JZgwLXHRMmn8czINDXcKSj/lU2GS7DGievebL
m/KmpSViXOxVwmw2J5v3Ww5W8xscDt0teITO0tQix8OJWpMpNOBTQ+coZRukgppB
Yc33k8N59vWyC2/z/gYtKZlWaiDVq3VpilHnY/bCowuNFGsQ9D+iUGcsH4wOTSnS
zVpEFO0WKp8bedrmWQ87JulDCRgcXXDA9wRmfnn3EQKBgQDdWWWaJXIt5lX5oTnE
30+FHJneEacvJTGtVlOSKjch6TbfiVm8qkpsjTMW0rd+yHlZOqqp5K1gUr/luZ5V
264RHEcL8bx/9BHXwXOqsg4r7BPSGm0YxrWRGE1LKuH015JZsYO8UJa/62nIqKJ/
ektg06IzN+oKQRoDa55n2yC60QKBgQDFCA5tmTs/AQ2bUCABWHn/cDfykE419lZY
ZHomTav2RIw9BeeBccDCGzhfH1AlnU1pnsEg/M4qzjFzExpqAgENWCvGrCJs6p7u
u8kwwaam7vx0RaY0PRaY5CsWzt/WZVuC9Ev4aY+iesZVmMyij56olXMN/jwgY9fa
KODz9aBJWQKBgB/+qQoD+aIa1jiUDmafpL3n6XHI+XJ+HNUiUkghZAC51h2vm9IC
h2lza3wUD0P7NFcqfLq7/DedHnHVR8a/T0TX4okecxHHtMCMDO0SeavtntvSyAw5
xMrpSVrhIvIiKtxeJV2WBIRPQeYoQfzNL5IaZSqkHWdIC7uM1cPLT8rRAoGATo38
uqOaJG92DlMuv3qYAUirdbElDYyuNkWxEa5r/h6sTvQYrdo9gOY7XmlsmeKSZ6bc
1xsT06srufaG1HcCFmDt6yLcAtK0FPiXqTG8ENg9nNnb/v3QEZr+tvQ5+A+nIZnm
5B6qHpyWkK///lwGZK5ZFd4j+MH14EvmDD4E7tkCgYBE/yIVbGUwk5ccN1pXGJma
RhWfxG3lmJV8MMrIpXEqy5hJgN+6sT1zDzkalyl9E23c0rEFbRt/Ol/Ir2aeP0N6
/fJ1AJ/D/Shl954/ecnmlDb7NJz4QbGkAxxz6YwmVbpf0LupXNqrD6uJxX3o+nx/
XVuYlDTG55DOKegQUL6tfA==
-----END PRIVATE KEY-----"""
client_email = "mood-log@mood-log-458400.iam.gserviceaccount.com"
client_id = "105788719869112063714"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/mood-log%40mood-log-458400.iam.gserviceaccount.com"
universe_domain = "googleapis.com"